dist: trusty
language: java
jdk: oraclejdk8
services:
  - docker
script:
  - docker build -t $DOCKER_IMAGE:latest .
deploy:
    provider: script
    script: bash docker_push
    on:
      all_branches: true
