dist: trusty
language: java
jdk: oraclejdk8
env:
  global:
    - PGUSER=postgres
    - PGPORT=5432
services:
  - docker
  - postgresql
before_script:
  - psql -c 'create database db;' -U postgres
script:
  - docker build -t captain-adhoc .
deploy:
    provider: script
    script: bash docker_push
    on:
      all_branches: true
