version: '3'
services: 
    web:
        build: .
        ports:
            - 8080:8080
        depends_on:
            - db

    db:
        container_name: db
        image: postgres:12
        environment:
            POSTGRES_DB: "db"
            POSTGRES_HOST_AUTH_METHOD: "trust"
            POSTGRES_USER: "postgres"
        ports:
            - 5432:5432