version: '3'
services:
    db:
        container_name: db
        image: postgres:12
        environment:
            POSTGRES_HOST_AUTH_METHOD: "trust"
            POSTGRES_USER: "postgres"
        ports:
            - 5432:5432
    web:
        build: .
        environment:
            - "SPRING_PROFILES_ACTIVE=dev"
            - "DATABASE_URL=db"
        ports:
            - 8080:8080
        depends_on:
            - db

