version: '3'
services: 
    web:
        build: .
        environment:
          API_URL: '"http://192.168.99.100:8080"'
        ports:
            - 8080:8080
        depends_on:
            - db


    db:
        container_name: db
        image: postgres:12
        environment:
            POSTGRES_DB: "db"
            POSTGRES_HOST_AUTH_METHOD: "trust"
        ports:
            - 5432:5432